### ISSUE TITLE
Fields under Run model not updating

### ISSUE THREAD

**Issue by isomemo** [Pandora-IsoMemo/plotr#11]
@arunge I uploaded the same Excel file twice. The first sheet was different for each case and each had different columns. However, the fields under "Data settings" under the tab "Run model" show the fields for the first upload and are not updated when I load the file the second time.

**Comment by arunge** [comment]
This is fixed with the [new version 22.11.1](https://github.com/Pandora-IsoMemo/plotr/pull/12#issue-1463729597) on [PlotR beta](https://isomemoapp.com/app/plotr-beta):
- When importing a second file with the same filename, now 
  - a number is added (1):
![image](https://user-images.githubusercontent.com/16759098/204253039-311eb05c-0052-410f-9fa8-e81522f8161e.png)
  - there is a new button to load a selected file and by this update the input fields (2):
![image](https://user-images.githubusercontent.com/16759098/204253496-3cdc1f72-9c62-458b-928b-4fa29d38f255.png)
