### ISSUE TITLE
New task within Style Plot

### ISSUE THREAD

**Issue by isomemo** [Pandora-IsoMemo/plotr#13]
@arunge New task for support contract: within "Plot style" we have two scrollers to set the ranges for x and y axes. However, it is very difficult to set the exact same ranges for two different graphs. You can keep the scrollers but add also the possibility of setting ranges using two input boxes. The user will enter numbers and can then press an "Ok" button to apply.

**Comment by arunge** [comment]
With [version 22.12.1](https://github.com/Pandora-IsoMemo/plotr/pull/15) on the [beta app](https://isomemoapp.com/app/plotr-beta). There is the option to use numeric inputs instead of sliders.
For this, I re-used a module that [already exists in the iso-app](https://github.com/Pandora-IsoMemo/iso-app/blob/4d0a70b28e322a8dd788c2527bb393825f80a05a/R/02-modules-modelResultHelpers.R#L794-L895), and modified it a little bit for sliders with two values. Therefor, I did not need to add a button. Both inputs (sliders and numeric fields) are updated respectively.
