### ISSUE TITLE
Possible bug but unclear

### ISSUE THREAD

**Issue by isomemo** [Pandora-IsoMemo/plotr#24]
@arunge @mgross 

For the attached dataset (x values with min/max range and y value as point) the graph output below is generated using default PlotR options. The SEM seems excessive. Bug?

[human upload.xlsx](https://github.com/Pandora-IsoMemo/plotr/files/10537417/human.upload.xlsx)

![image](https://user-images.githubusercontent.com/46485054/215527016-f5bba262-bb1b-4595-a807-c3082f7f2c74.png)

**Comment by arunge** [comment]
@mgross Since this question is related to model output, could you advice here?

**Comment by isomemo** [comment]
@arunge @mgross any updates on this?

**Comment by mgross** [comment]
@isomemo:

This happened, because the sample size is so low and therefore standard deviation estimation was quite unstable. This lead to such large intervals. As the prior for sigma (standard deviation) was very wide (or almost non-informative) a solution is to tighten the prior somewhat, namely from IG(1E-5,1E-5) to IG(0.5, 1E-5). That makes sense as the data is standardized internally and values far from 1 for sigma don't make sense usually.

I think the intervals are much more reasonable now (and for larger sample sizes the results stay the same as I tested on some examples):

![grafik](https://user-images.githubusercontent.com/5138071/222758566-f7947289-f82f-4b65-ab2a-324d248b5055.png)

Note however, that estimating the standard deviation (and therefore also SEM) is not really reliable for such low sample sizes and nonlinear models.

@arunge: I opened a pull request for this.

**Comment by isomemo** [comment]
@mgross thanks for this! So, the current graph shows:

1) Continous line: mean of the mean parameter?
2) Discontinuous lines: mean of SD parameter + mean of the mean parameter?

**Comment by arunge** [comment]
@mgross Maybe it could help to add a warning for too little sample sizes? If you could tell a minimal sample size `XY`, I could add the warning.
Maybe something like:

"Warning!
Estimation of the standard deviation / the SEM with nonlinear models is not reliable for sample sizes below `XY`. Please, use a larger sample size!"

**Comment by mgross** [comment]
@arunge: Everything below 8, I would say (but not strictly necessary).
@isomemo: 1) Yes
No, more like SD of mean parameter + mean of mean parameter. 

The plot shows the mean uncertainty ("SEM"), i.e. with the given Quantile Coverage (default 95%). That means that for a given x (time point), the probability that the true mean lies within the discontinuous lines is 95%.

Mean of SD parameter + mean of the mean parameter would be "SD" choice.

The total error (SEM + SD: "SEM Total") means that any unknown observations would lie between the discontinuous lines.

(I would rather prefer "mean", "error" and "total" in the uncertainty selection instead of SEM, SD and SEM TOTAL as we have the quantile selection

**Comment by arunge** [comment]
@isomemo Is it enough to add a warning for too little sample sizes?

> "Warning!
> Estimation of the standard deviation / the SEM with nonlinear models is not reliable for sample sizes below 8. Please, use a larger sample size to increase reliability!"

Or do we need something else here?

**Comment by isomemo** [comment]
@arunge use this instead: "Warning! Estimation of the standard deviation / the SEM with nonlinear models may not be reliable for sample sizes below 8."

However, let the user run the model

**Comment by arunge** [comment]
With [version 23.03.3](https://github.com/Pandora-IsoMemo/plotr/pull/31) the warning was added as desired to the beta version.
