### ISSUE TITLE
Select inputs under data settings

### ISSUE THREAD

**Issue by isomemo** [Pandora-IsoMemo/plotr#26]
@arunge under Data Settings it is no longer possible to select variables (Select x and Select y). The input box reads "Load a file"

**Comment by arunge** [comment]
In PlotR it is possible to upload more than one file with (1). 

![image](https://user-images.githubusercontent.com/16759098/222368644-a26d5807-9cf7-4d59-aec9-dd199124d3f3.png)

Since automatic updates of all tabs whenever a user decides to upload new files can lead to undesired behaviour (e.g. plots should be reset and other inputs should be reset,...), the solution was to disable automatic updates for file uploads. So, the user has to explicitly select the desired file under "Run Model" and _Load_ (2) it to enable column selection (3) and modelling. By this, it should always be clear to the user which data is used in the tab "Run Model" for columns and modeling.

![image](https://user-images.githubusercontent.com/16759098/222369387-c28c1822-7cc1-47e5-958c-90c1316ffff8.png)

@isomemo I could rephrase the note in (4) into "Select a file ..." and rename the button (5) to "Select". Should we change this?

![image](https://user-images.githubusercontent.com/16759098/222370528-ec44ea27-af24-4470-b59e-0e0b29a00617.png)

**Comment by arunge** [comment]
@isomemo As discussed I updated the title of the input (1). This fix is already available for both, the [main](https://isomemoapp.com/app/plotr) and the [beta](https://isomemoapp.com/app/plotr-beta) version.

![image](https://user-images.githubusercontent.com/16759098/232859482-c17bac2e-b985-42a7-a7d0-cf4c23194192.png)
