### ISSUE TITLE
No model output/crash

### ISSUE THREAD

**Issue by isomemo** [Pandora-IsoMemo/plotr#8]
@arunge 

I loaded this file:

[China_isotopes_data_R2_D29.xls](https://github.com/Pandora-IsoMemo/plotr/files/9714878/China_isotopes_data_R2_D29.xls)

I tried to create a PlotR model using the settings shown below (I also tried with a different number of basis functions):

![image](https://user-images.githubusercontent.com/46485054/194040686-9da0ed7f-6ede-41ba-bf46-abd256a67194.png)

I did this yesterday and nothing happened. I tried this again today and the app now crashed. There was a difference relative to yesterday, before loading the Excel file above I had previously loaded two other files. I do not think that this is the reason for the crash but decided to mention it anyway. Perhaps the reason for the no output yesterday/crash today could be the fact that there are some rows with missing data.

**Comment by arunge** [comment]
Because of NA values the column was not identified as numeric after importing the file. I fixed this with [version 22.11.1](https://github.com/Pandora-IsoMemo/plotr/pull/12#issue-1463729597) on [PlotR beta](https://isomemoapp.com/app/plotr-beta):
- As long as there are values left after one would transform a column to `numeric`, the column will be selectable in the input field. If selected, than the column will be transformed to numeric and all NA values will be deleted, automatically.
